import { Router } from 'express';
import crypto from 'crypto';
import bcrypt from 'bcrypt';
import { prisma } from '../config/database';
import { authenticateToken, authorizeRoles } from '../middleware/auth';
import { formatResponse } from '../utils/apiResponse';
import { asyncHandler } from '../utils/asyncHandler';
import { ApiError } from '../utils/apiError';
import { MailService } from '../services/mail.service';
import { logAudit } from '../utils/auditLogger';
import { NotificationService } from '../services/notification.service';

const router = Router();

// Onboard New Officer (restricted to SUPER_ADMIN)
router.post('/onboard-officer', authenticateToken, authorizeRoles('SUPER_ADMIN'), asyncHandler(async (req: any, res: any) => {
  const { officerId, email, name, role, department, rank } = req.body;

  if (!officerId || !email || !name || !role || !department || !rank) {
    throw new ApiError(400, 'Missing officer onboarding details: officerId, email, name, role, department, rank.');
  }

  const existingUser = await prisma.user.findUnique({
    where: { email }
  });
  if (existingUser) {
    throw new ApiError(400, 'Officer email already registered.');
  }

  const existingOfficer = await prisma.officer.findUnique({
    where: { id: officerId }
  });
  if (existingOfficer) {
    throw new ApiError(400, 'Officer ID already registered.');
  }

  // Generate a temporary random password
  const temporaryPassword = crypto.randomBytes(6).toString('hex');

  // Hash the password using bcrypt before storing it
  const hashedPassword = await bcrypt.hash(temporaryPassword, 10);

  // Save the officer's email, role, and department
  const user = await prisma.user.create({
    data: {
      id: officerId,
      email,
      name,
      password: hashedPassword,
      role,
      department,
      passwordChangeRequired: true
    }
  });

  const officer = await prisma.officer.create({
    data: {
      id: officerId,
      rank,
      avatar: `https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=120`
    }
  });

  // Send a welcome email containing credentials
  await MailService.sendWelcomeEmail(email, name, officerId, temporaryPassword);

  await logWorkflowAction(req, req.user.officerId, req.user.role, 'Officer Onboarded', `Onboarded Officer ID: ${officerId} (${name}).`);

  await NotificationService.notifyAll(`Officer Onboarded: New official ${name} added under ID ${officerId}.`, 'System').catch(console.error);

  res.json(formatResponse({ officerId, email, name, role, department, rank }, 'Officer onboarded successfully. Credentials emailed.'));
}));

// Helper: Log workflow actions globally with role and IP address mapping
async function logWorkflowAction(req: any, userId: string, role: string, action: string, details: string, caseId?: string) {
  await logAudit(req, userId, role, action, details, caseId);
}

// 1. Register FIR (Sub Inspector)
router.post('/register-fir', authenticateToken, authorizeRoles('SUPER_ADMIN', 'SUB_INSPECTOR'), asyncHandler(async (req: any, res: any) => {
  const { id, title, description, reporter } = req.body;
  if (!id || !title || !description || !reporter) {
    throw new ApiError(400, 'Missing FIR param details.');
  }

  const fir = await prisma.fir.create({
    data: {
      id,
      title,
      description,
      reporter,
      date: new Date().toISOString().split('T')[0],
      officerId: req.user.officerId
    }
  });

  await logWorkflowAction(req, req.user.officerId, req.user.role, 'FIR Registered', `FIR ID: ${id} registered by Sub Inspector.`);
  
  await NotificationService.notifyAll(`New FIR Registered: Reference "${title}" (ID: ${id}) logged by SI.`, 'Info').catch(console.error);

  res.json(formatResponse(fir, 'FIR registered successfully.'));
}));

// 2. Create Case (Sub Inspector)
router.post('/create-case', authenticateToken, authorizeRoles('SUPER_ADMIN', 'SUB_INSPECTOR'), asyncHandler(async (req: any, res: any) => {
  const { id, title, crimeType, priority, location, firId, assignedOfficerId, victimName, suspectName } = req.body;

  if (!id || !title || !crimeType || !priority || !location || !firId || !assignedOfficerId || !victimName || !suspectName) {
    throw new ApiError(400, 'Missing required case initialization parameters.');
  }

  const newCase = await prisma.case.create({
    data: {
      id,
      title,
      crimeType,
      priority,
      officerId: assignedOfficerId,
      location,
      status: 'Active',
      victims: {
        create: [
          { name: victimName }
        ]
      },
      suspects: {
        create: [
          { name: suspectName }
        ]
      },
      timeline: {
        create: [
          { step: 'First Information Report (FIR) Filed', completed: true, details: `Registered under reference ID: ${firId}` },
          { step: 'Investigation Case File Opened', completed: true, details: 'Case file generated by Sub Inspector.' },
          { step: 'Officer Assignment & Briefing', completed: true, details: `Assigned to Officer ID: ${assignedOfficerId}` },
          { step: 'Investigation Underway', completed: true, details: 'Officer briefed on initial FIR findings.' }
        ]
      },
      caseNotes: {
        create: [
          { note: `Case initialized from FIR. Assigned Officer ID: ${assignedOfficerId}. Victim: ${victimName}. Suspect: ${suspectName}.`, author: req.user.name }
        ]
      },
      firId
    }
  });

  await logWorkflowAction(req, req.user.officerId, req.user.role, 'Case Created', `Case ${id} created from FIR ${firId} and assigned to ${assignedOfficerId}.`, id);
  
  await NotificationService.createNotification(assignedOfficerId, `Case Assigned: You have been assigned to case ${id}.`, 'Assignment').catch(console.error);
  await NotificationService.notifyAll(`Case Opened: New criminal case "${title}" (ID: ${id}) initialized and assigned to Officer ID ${assignedOfficerId}.`, 'Info').catch(console.error);

  res.json(formatResponse(newCase, 'Case file created successfully.'));
}));

// 3. Assign Inspector (Superintendent / SP)
router.post('/assign-inspector', authenticateToken, authorizeRoles('SUPER_ADMIN', 'SUPERINTENDENT'), asyncHandler(async (req: any, res: any) => {
  const { caseId, inspectorId } = req.body;

  const updatedCase = await prisma.case.update({
    where: { id: caseId },
    data: {
      officerId: inspectorId
    }
  });

  await logWorkflowAction(req, req.user.officerId, req.user.role, 'Case Assigned', `Case assigned to Inspector ID ${inspectorId}.`, caseId);
  
  // Update timeline
  await prisma.timeline.updateMany({
    where: { caseId, step: 'Officer Assignment & Briefing' },
    data: { completed: true, details: `Assigned to Inspector ID: ${inspectorId}` }
  });

  await prisma.timeline.create({
    data: {
      caseId,
      step: 'Investigation Underway',
      completed: true,
      details: `Inspector assigned by SP. Officer ID: ${inspectorId}`
    }
  });

  // Notify assigned inspector via DB & Socket
  await NotificationService.createNotification(inspectorId, `Case Assigned: You have been assigned to case ${caseId}.`, 'Assignment').catch(console.error);
  await NotificationService.notifyAll(`Case Assignment: Case ${caseId} assigned to Officer ID ${inspectorId}.`, 'Info').catch(console.error);

  res.json(formatResponse(updatedCase, 'Inspector assigned successfully.'));
}));

// 4. Request Forensic Analysis (Inspector)
router.post('/request-forensic', authenticateToken, authorizeRoles('SUPER_ADMIN', 'INSPECTOR'), asyncHandler(async (req: any, res: any) => {
  const { reportId, caseId, type, summary } = req.body;

  const report = await prisma.forensicReport.create({
    data: {
      id: reportId,
      caseId,
      type,
      analyst: req.user.name,
      status: 'Pending Analysis',
      summary,
      approvalDate: 'Awaiting Report Upload'
    }
  });

  await logWorkflowAction(req, req.user.officerId, req.user.role, 'Forensic Requested', `Forensic analysis requested for case ${caseId}.`, caseId);
  
  await prisma.timeline.create({
    data: {
      caseId,
      step: 'Forensic Lab Analysis Requested',
      completed: true,
      details: `Type: ${type}. Ref ID: ${reportId}`
    }
  });

  await NotificationService.notifyRole('FORENSIC_OFFICER', `Forensic Request: New analysis requested for case ${caseId}.`, 'Assignment').catch(console.error);

  res.json(formatResponse(report, 'Forensic report request generated.'));
}));

// 5. Submit Forensic Findings (Forensic Officer)
router.post('/submit-forensic', authenticateToken, authorizeRoles('SUPER_ADMIN', 'FORENSIC_OFFICER'), asyncHandler(async (req: any, res: any) => {
  const { reportId, summary } = req.body;

  const report = await prisma.forensicReport.update({
    where: { id: reportId },
    data: {
      summary,
      status: 'Pending Approval',
      approvalDate: 'Awaiting Superintendent Approval'
    }
  });

  await logWorkflowAction(req, req.user.officerId, req.user.role, 'Forensic Findings Submitted', `Findings submitted for report ${reportId}.`, report.caseId);
  
  await prisma.timeline.create({
    data: {
      caseId: report.caseId,
      step: 'Forensic Findings Ingested',
      completed: true,
      details: `Report ID: ${reportId}. Status: Pending SP Review.`
    }
  });

  await NotificationService.notifyRole('SUPERINTENDENT', `Forensic Report Submitted: Analysis complete for report ${reportId}.`, 'Alert').catch(console.error);

  res.json(formatResponse(report, 'Forensic findings submitted for review.'));
}));

// 6. Complete Investigation (Inspector)
router.post('/complete-investigation', authenticateToken, authorizeRoles('SUPER_ADMIN', 'INSPECTOR'), asyncHandler(async (req: any, res: any) => {
  const { caseId } = req.body;
  if (!caseId) throw new ApiError(400, 'Missing caseId.');
  
  await logWorkflowAction(req, req.user.officerId, req.user.role, 'Investigation Completed', 'Investigation completed and submitted for Superintendent review.', caseId);

  await prisma.timeline.create({
    data: {
      caseId,
      step: 'Investigation Logged as Complete',
      completed: true,
      details: 'Inspector submitted case file to Superintendent for final chargesheet sign-off.'
    }
  });

  await NotificationService.notifyRole('SUPERINTENDENT', `Case Investigation Complete: Case ${caseId} awaiting SP review.`, 'Alert').catch(console.error);

  res.json(formatResponse({ caseId }, 'Investigation marked as completed and submitted for review.'));
}));

// 7. Review Case (Superintendent)
router.post('/review-case', authenticateToken, authorizeRoles('SUPER_ADMIN', 'SUPERINTENDENT'), asyncHandler(async (req: any, res: any) => {
  const { caseId, notes } = req.body;
  if (!caseId || !notes) throw new ApiError(400, 'Missing caseId or notes.');
  
  await logWorkflowAction(req, req.user.officerId, req.user.role, 'Case Reviewed', `Case reviewed by Superintendent. Notes: ${notes}`, caseId);

  await prisma.timeline.create({
    data: {
      caseId,
      step: 'Superintendent Review Logged',
      completed: true,
      details: `Review Note Excerpt: "${notes.slice(0, 50)}..."`
    }
  });

  await NotificationService.notifyAll(`Case Reviewed: Superintendent logged review notes for Case ${caseId}.`, 'Info').catch(console.error);

  res.json(formatResponse({ caseId }, 'Case review completed and logged.'));
}));

// 8. Approve Chargesheet & Close Case (Superintendent)
router.post('/approve-chargesheet', authenticateToken, authorizeRoles('SUPER_ADMIN', 'SUPERINTENDENT'), asyncHandler(async (req: any, res: any) => {
  const { caseId } = req.body;

  const closedCase = await prisma.case.update({
    where: { id: caseId },
    data: {
      status: 'Solved'
    }
  });

  await logWorkflowAction(req, req.user.officerId, req.user.role, 'Chargesheet Approved', `Chargesheet approved and Case ${caseId} marked SOLVED.`, caseId);
  
  await prisma.timeline.create({
    data: {
      caseId,
      step: 'Case Closed & Resolved',
      completed: true,
      details: 'Chargesheet approved by Superintendent. Status: SOLVED.'
    }
  });

  await NotificationService.notifyAll(`Case Closed: Superintendent approved chargesheet. Case ${caseId} marked SOLVED.`, 'System').catch(console.error);

  res.json(formatResponse(closedCase, 'Chargesheet approved and case closed successfully.'));
}));

export default router;
export { logWorkflowAction };
